[package]
name = "xfade"
version = "0.1.0"
authors = ["Alex Norman <alex@x37v.info>"]
edition = "2018"

[lib]
name = "xfade_tilde"
crate-type = ["cdylib"]

[dependencies]
pd-sys = "0.1.0"
pd-ext = { path = "../../../external" }
pd-ext-macros = { path = "../.." }
itertools = "0.8.0"
num = "0.2.0"
